#ifndef ERROR_CODES_H
#define ERROR_CODES_H

/*******************************************************************************
 * Types, constants
 ******************************************************************************/
typedef enum {
	SIRONA_DRIVER_LIMIT_ERROR = -1,

	SIRONA_DRIVER_NO_ERROR = 0,

	/* Errors returned by the device with the NOK response packet 1 - 50 */
	SIRONA_DEVICE_COMMAND_NOT_IMPLEMENTED = 1,
	SIRONA_DEVICE_MEMORY_ERROR,
	SIRONA_DEVICE_IO_ERROR,
	SIRONA_DEVICE_ILLEGAL_VALUE,
	SIRONA_DEVICE_PARAMETER_UNMODIFIABLE,
	SIRONA_DEVICE_ILLEGAL_PARAMETER,
	SIRONA_DEVICE_INVALID_EVENT_NUMBER,
	SIRONA_DEVICE_DATA_OUT_OF_RANGE,
	SIRONA_DEVICE_CHALLENGE_INCORRECT,
	SIRONA_DEVICE_CABLE_UNPLUGGED,
	SIRONA_DEVICE_INCORRECT_CABLE_PLUGGED,
	SIRONA_DEVICE_PROCEDURE_STARTED_CONFIGURATION_UNMODIFIABLE,
	SIRONA_DEVICE_FILE_NOT_AVAILABLE,

	/* General errors 51 - 100 */
	SIRONA_DRIVER_FAILED_TO_ALLOCATE = 51,
	SIRONA_DRIVER_NO_MORE_DEVICES,
	SIRONA_DRIVER_INVALID_HANDLE,
	SIRONA_DRIVER_INVALID_PARAMETER,

	/* Device operations errors 101 - 150 */
	SIRONA_DRIVER_FAILED_TO_OPEN_DEVICE = 101,
	SIRONA_DRIVER_FAILED_TO_CLOSE_DEVICE,
	SIRONA_DRIVER_FAILED_TO_GET_DEVICES_CONFIGURATION,
	SIRONA_DRIVER_FAILED_TO_SET_DEVICES_CONFIGURATION,
	SIRONA_DRIVER_FAILED_TO_GET_DEVICES_TIMEOUTS,
	SIRONA_DRIVER_FAILED_TO_SET_DEVICES_TIMEOUTS,
	SIRONA_DRIVER_FAILED_TO_READ_FROM_DEVICE,
	SIRONA_DRIVER_FAILED_TO_WRITE_TO_DEVICE,
	/* Bluetooth Device */
	SIRONA_DRIVER_BLUETOOTH_MODE_NOT_PRESENT,
	SIRONA_DRIVER_BLUETOOTH_PAIRING_ERROR,
	SIRONA_DRIVER_BLUETOOTH_DISCOVERY_IN_PROCESS,
	SIRONA_DRIVER_BLUETOOTH_DISCOVERY_ERROR,

	/* Network layer errors 151 - 200 */
	SIRONA_DRIVER_NETWORK_INVALID_INPUT_PARAMETERS = 151,
	SIRONA_DRIVER_NETWORK_ZERO_BYTES_READ_FROM_DEVICE,
	SIRONA_DRIVER_NETWORK_TO_MANY_GARBAGE_READ_FROM_DEVICE,
	SIRONA_DRIVER_NETWORK_FAILED_TO_READ_THE_REST_OF_THE_HEADER_IN_50_MSEC,
	SIRONA_DRIVER_NETWORK_FAILED_TO_READ_WHOLE_PACKET_IN_500_MSEC,
	SIRONA_DRIVER_NETWORK_CRC_MISMATCH,
	SIRONA_DRIVER_NETWORK_WRONG_SEQUNCE_NUMBER,
	SIRONA_DRIVER_NETWORK_INVALID_PACKET_TYPE,
	SIRONA_DRIVER_NETWORK_UNEXPECTED_PACKET_TYPE,
	SIRONA_DRIVER_NETWORK_DATA_PACKET_NOT_RECEIVED_IN_EXPECTED_TIMEFRAME,
	SIRONA_DRIVER_NETWORK_RESPONSE_NOT_RECEIVED_AFTER_THREE_RETRIES,

	/* Protocol layer errors 201 - 250 */
	SIRONA_DRIVER_PROTOCOL_INVALID_INPUT_PARAMETERS = 201,
	SIRONA_DRIVER_PROTOCOL_INVALID_RESPONSE_APPDATA_PACKAGE_LOCATION,
	SIRONA_DRIVER_PROTOCOL_WRONG_COMMAND_RESPONSE_RECEIVED,
	SIRONA_DRIVER_PROTOCOL_BUFFER_ALLOCATED_FOR_COMMAND_RESPONSE_IS_TOO_LOW,
	SIRONA_DRIVER_PROTOCOL_COMMAND_RESPONSE_SIZE_NOT_EXPECTED,
	SIRONA_DRIVER_PROTOCOL_PARAMETER_NAME_TOO_LONG,
	SIRONA_DRIVER_PROTOCOL_PARAMETER_VALUE_TOO_LONG,

	/* Sirona application errors 251 - 300 */
	SIRONA_APPLICATION_WRONG_BULK_SEQUENCE_NUMBER

} error_code_t;

typedef struct {
	const error_code_t errCode;
	const char *const errString;
} error_struct_t;

#endif // ERROR_CODES_H
